function u = loupas_3D(I_kern, Q_kern)
%LOUPAS_3D Calculate initial displacement estimation for a collection of
% 3D kernels.

% Preallocate displacement data
u = zeros(size(I_kern, [1, 2, 3]));

% Calculate axial and ensemble windows
win_z_F = 1:size(I_kern, 4);
win_z_f = 1:(size(I_kern, 4)-1);
win_t_F = 1:(size(I_kern, 6)-1);
win_t_f = 1:size(I_kern, 6);

for z = 1:size(I_kern, 1)
    for x = 1:size(I_kern, 2)
        for t = 1:size(I_kern, 3)

            % Squeeze kernel to 3D
            IData = squeeze(I_kern(z, x, t, :, :, :));
            QData = squeeze(Q_kern(z, x, t, :, :, :));

            % Calculate frequency estimates
            F_0 = atan(...
                sum( ...
                (QData(win_z_F, :, win_t_F) .* ...
                IData(win_z_F, :, win_t_F + 1) - ...
                IData(win_z_F, :, win_t_F) .* ...
                QData(win_z_F, :, win_t_F + 1)), 'all') / ...
                sum( ...
                (IData(win_z_F, :, win_t_F) .* ...
                IData(win_z_F, :, win_t_F + 1) + ...
                QData(win_z_F, :, win_t_F) .* ...
                QData(win_z_F, :, win_t_F + 1)), 'all')) / (2*pi);
        
            f_dopp = atan(...
                sum( ...
                (QData(win_z_f, :, win_t_f) .* ...
                IData(win_z_f + 1, :, win_t_f) - ...
                IData(win_z_f, :, win_t_f) .* ...
                QData(win_z_f + 1, :, win_t_f)), 'all') / ...
                sum( ...
                (IData(win_z_f, :, win_t_f) .* ...
                IData(win_z_f + 1, :, win_t_f) + ...
                QData(win_z_f, :, win_t_f) .* ...
                QData(win_z_f + 1, :, win_t_f)), 'all')) / (2*pi);
        
            % Estimate inter-frame displacement [wvls]
            u(z, x, t) = - F_0 / (1 + f_dopp);
        end
    end
end


end

