function PData = BMS_PData(P, Trans)
% Define PData object.

% Define pixel resolution in wavelengths
x_res = 0.5; % Consider changing it to 0.5
z_res = 0.25; % Consider changing it to 0.25

PData(1) = struct( ...
    'PDelta', ... % voxel resolution (X, Y ,Z)
            [x_res, 0, z_res], ... 
    'Size', ...   % imageBuffer dimensions (Z, X, Frames)
            [ceil((P.endDepth - P.startDepth) / z_res), ... 
            ceil(P.latDist / x_res), ...
            1], ...
    'Origin', ... % upper left corner (X, Y, Z)
            [0, ...
            0, ...
            P.startDepth]);

end
